"""
Migration script to export SQLite data and import to PostgreSQL (Supabase).

This script:
1. Exports all data from SQLite database to SQL format
2. Generates PostgreSQL-compatible SQL statements
3. Can directly import to PostgreSQL if connection string provided

Usage:
    # Export to SQL file only
    python scripts/migrate_to_postgresql.py --export-only --output migration.sql

    # Export and import directly to PostgreSQL
    python scripts/migrate_to_postgresql.py --postgres-url "postgresql://user:pass@host:5432/db"  # pragma: allowlist secret

    # Dry run (show what would be migrated)
    python scripts/migrate_to_postgresql.py --dry-run
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

from database.models import CVE, ChatMessage, ChatSession, Dependency, Scan


def export_table_to_sql(session, model, file_handle):
    """Export table data to PostgreSQL-compatible SQL INSERT statements."""
    table_name = model.__tablename__
    records = session.query(model).all()

    if not records:
        print(f"  No records in {table_name}")
        return 0

    print(f"  Exporting {len(records)} records from {table_name}...")

    # Get column names (excluding relationships)
    columns = [col.name for col in model.__table__.columns]

    # Write table header
    file_handle.write(f"\n-- Table: {table_name}\n")
    file_handle.write(f"-- Records: {len(records)}\n\n")

    # Generate INSERT statements
    for record in records:
        values = []
        for col in columns:
            value = getattr(record, col)

            # Handle different data types
            if value is None:
                values.append("NULL")
            elif isinstance(value, str):
                # Escape single quotes for SQL
                escaped = value.replace("'", "''")
                values.append(f"'{escaped}'")
            elif isinstance(value, datetime):
                values.append(f"'{value.isoformat()}'")
            elif isinstance(value, (dict, list)):
                # JSON columns
                json_str = json.dumps(value).replace("'", "''")
                values.append(f"'{json_str}'")
            elif isinstance(value, bool):
                values.append("TRUE" if value else "FALSE")
            else:
                values.append(str(value))

        # Build INSERT statement
        cols_str = ", ".join(columns)
        vals_str = ", ".join(values)
        file_handle.write(
            f"INSERT INTO {table_name} ({cols_str}) VALUES ({vals_str});\n"  # noqa: S608
        )

    return len(records)


def create_postgresql_schema(file_handle):
    """Generate PostgreSQL schema creation statements."""
    file_handle.write(
        """-- PostgreSQL Schema for CyberIntel Summarizer
-- Generated by migrate_to_postgresql.py

-- Drop existing tables (optional, comment out if you want to keep existing data)
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS scan_cves CASCADE;
DROP TABLE IF EXISTS dependencies CASCADE;
DROP TABLE IF EXISTS scans CASCADE;
DROP TABLE IF EXISTS cves CASCADE;

-- Table: cves
CREATE TABLE cves (
    cve_id VARCHAR(20) PRIMARY KEY,
    description TEXT NOT NULL,
    published_date TIMESTAMP NOT NULL,
    last_modified TIMESTAMP NOT NULL,
    severity VARCHAR(20),
    cvss_score FLOAT,
    cvss_vector VARCHAR(100),
    attack_vector VARCHAR(20),
    attack_complexity VARCHAR(20),
    privileges_required VARCHAR(20),
    user_interaction VARCHAR(20),
    vendor VARCHAR(100),
    product VARCHAR(100),
    version VARCHAR(50),
    source VARCHAR(20) NOT NULL DEFAULT 'NVD',
    references JSONB,
    cwe_ids JSONB,
    summary TEXT,
    summary_generated_at TIMESTAMP,
    raw_data JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_cves_published_date ON cves(published_date);
CREATE INDEX idx_cves_last_modified ON cves(last_modified);
CREATE INDEX idx_cves_severity ON cves(severity);
CREATE INDEX idx_cves_vendor ON cves(vendor);
CREATE INDEX idx_cves_source ON cves(source);

-- Table: scans
CREATE TABLE scans (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(36),
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    file_hash VARCHAR(64),
    scan_date TIMESTAMP NOT NULL DEFAULT NOW(),
    total_dependencies INTEGER DEFAULT 0,
    vulnerable_dependencies INTEGER DEFAULT 0,
    total_cves INTEGER DEFAULT 0,
    critical_count INTEGER DEFAULT 0,
    high_count INTEGER DEFAULT 0,
    medium_count INTEGER DEFAULT 0,
    low_count INTEGER DEFAULT 0,
    raw_content TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_scans_user_id ON scans(user_id);

-- Table: dependencies
CREATE TABLE dependencies (
    id SERIAL PRIMARY KEY,
    scan_id INTEGER NOT NULL REFERENCES scans(id) ON DELETE CASCADE,
    package_name VARCHAR(255) NOT NULL,
    version VARCHAR(100) NOT NULL,
    version_constraint VARCHAR(100),
    ecosystem VARCHAR(50) NOT NULL,
    cpe_uri VARCHAR(255),
    cpe_match_confidence FLOAT,
    is_vulnerable INTEGER DEFAULT 0,
    cve_count INTEGER DEFAULT 0,
    highest_severity VARCHAR(20),
    package_metadata JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dependencies_scan_id ON dependencies(scan_id);
CREATE INDEX idx_dependencies_package_name ON dependencies(package_name);

-- Table: scan_cves (association table)
CREATE TABLE scan_cves (
    scan_id INTEGER NOT NULL REFERENCES scans(id) ON DELETE CASCADE,
    cve_id VARCHAR(20) NOT NULL REFERENCES cves(cve_id) ON DELETE CASCADE,
    dependency_id INTEGER NOT NULL REFERENCES dependencies(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (scan_id, cve_id)
);

-- Table: chat_sessions
CREATE TABLE chat_sessions (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(36),
    scan_id INTEGER REFERENCES scans(id) ON DELETE CASCADE,
    title VARCHAR(255),
    session_type VARCHAR(20) NOT NULL DEFAULT 'project',
    selected_dependency_ids JSONB,
    context_injected INTEGER NOT NULL DEFAULT 0,
    dependency_context_hash VARCHAR(64),
    last_context_used_at TIMESTAMP,
    context_usage_count INTEGER NOT NULL DEFAULT 0,
    context_stack TEXT,
    enabled_features TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    last_message_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_sessions_user_id ON chat_sessions(user_id);
CREATE INDEX idx_chat_sessions_scan_id ON chat_sessions(scan_id);

-- Table: chat_messages
CREATE TABLE chat_messages (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    context_cves JSONB,
    rag_query TEXT,
    context_injected INTEGER NOT NULL DEFAULT 0,
    context_dependency_count INTEGER,
    input_tokens INTEGER,
    output_tokens INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_messages_session_id ON chat_messages(session_id);

-- Update timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply triggers to tables with updated_at
CREATE TRIGGER update_cves_updated_at BEFORE UPDATE ON cves
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_scans_updated_at BEFORE UPDATE ON scans
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_dependencies_updated_at BEFORE UPDATE ON dependencies
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

"""
    )


def migrate_sqlite_to_postgresql(
    sqlite_path: str = "cyberintel.db",
    output_file: str = "migration.sql",
    postgres_url: str = None,
    dry_run: bool = False,
):
    """
    Migrate data from SQLite to PostgreSQL.

    Args:
        sqlite_path: Path to SQLite database file
        output_file: Path to output SQL file
        postgres_url: PostgreSQL connection URL (if importing directly)
        dry_run: If True, only show statistics without writing files
    """
    # Check if SQLite database exists
    if not Path(sqlite_path).exists():
        print(f"Error: SQLite database not found at {sqlite_path}")
        sys.exit(1)

    # Connect to SQLite
    print(f"Connecting to SQLite database: {sqlite_path}")
    sqlite_engine = create_engine(f"sqlite:///{sqlite_path}")
    SQLiteSession = sessionmaker(bind=sqlite_engine)
    sqlite_session = SQLiteSession()

    # Get statistics
    print("\nAnalyzing database...")
    stats = {
        "cves": sqlite_session.query(CVE).count(),
        "scans": sqlite_session.query(Scan).count(),
        "dependencies": sqlite_session.query(Dependency).count(),
        "chat_sessions": sqlite_session.query(ChatSession).count(),
        "chat_messages": sqlite_session.query(ChatMessage).count(),
    }

    print("\nDatabase Statistics:")
    print("-" * 40)
    for table, count in stats.items():
        print(f"  {table:20} {count:>10,} records")
    print("-" * 40)
    print(f"  {'TOTAL':20} {sum(stats.values()):>10,} records")

    if dry_run:
        print("\nDry run complete. No files written.")
        return

    # Export to SQL file
    print(f"\nExporting to SQL file: {output_file}")
    with open(output_file, "w", encoding="utf-8") as f:
        # Write schema
        print("  Creating PostgreSQL schema...")
        create_postgresql_schema(f)

        # Export data in dependency order
        print("\nExporting data:")
        export_table_to_sql(sqlite_session, CVE, f)
        export_table_to_sql(sqlite_session, Scan, f)
        export_table_to_sql(sqlite_session, Dependency, f)

        # Export scan_cves association table manually
        f.write("\n-- Table: scan_cves (association table)\n\n")
        scan_cves = sqlite_session.execute(
            text("SELECT scan_id, cve_id, dependency_id, created_at FROM scan_cves")
        ).fetchall()
        if scan_cves:
            print(f"  Exporting {len(scan_cves)} records from scan_cves...")
            for row in scan_cves:
                scan_id, cve_id, dependency_id, created_at = row
                f.write(
                    f"INSERT INTO scan_cves (scan_id, cve_id, dependency_id, created_at) "  # noqa: S608
                    f"VALUES ({scan_id}, '{cve_id}', {dependency_id}, '{created_at}');\n"
                )

        export_table_to_sql(sqlite_session, ChatSession, f)
        export_table_to_sql(sqlite_session, ChatMessage, f)

        # Write completion message
        f.write("\n-- Migration complete!\n")
        f.write(f"-- Total records: {sum(stats.values())}\n")
        f.write(f"-- Generated: {datetime.now().isoformat()}\n")

    print(f"\n✓ SQL export complete: {output_file}")

    # If PostgreSQL URL provided, import directly
    if postgres_url:
        print(
            f"\nImporting to PostgreSQL: {postgres_url.split('@')[1] if '@' in postgres_url else postgres_url}"
        )
        try:
            pg_engine = create_engine(postgres_url)

            # Read SQL file and execute
            with open(output_file, encoding="utf-8") as f:
                sql_content = f.read()

            # Split into individual statements and execute
            with pg_engine.connect() as conn:
                # Execute schema creation
                print("  Creating schema...")
                conn.execute(text(sql_content))
                conn.commit()

            print("✓ Import complete!")

            # Verify import
            print("\nVerifying import...")
            PGSession = sessionmaker(bind=pg_engine)
            pg_session = PGSession()

            pg_stats = {
                "cves": pg_session.query(CVE).count(),
                "scans": pg_session.query(Scan).count(),
                "dependencies": pg_session.query(Dependency).count(),
                "chat_sessions": pg_session.query(ChatSession).count(),
                "chat_messages": pg_session.query(ChatMessage).count(),
            }

            print("\nPostgreSQL Statistics:")
            print("-" * 40)
            for table, count in pg_stats.items():
                sqlite_count = stats[table]
                status = "✓" if count == sqlite_count else "✗"
                print(f"  {status} {table:20} {count:>10,} / {sqlite_count:>10,}")
            print("-" * 40)

            if stats == pg_stats:
                print("\n✓ Migration verified successfully!")
            else:
                print("\n⚠ Warning: Record counts don't match. Please review.")

        except Exception as e:
            print(f"\n✗ Error importing to PostgreSQL: {e}")
            print(f"  You can manually import the SQL file: {output_file}")
            sys.exit(1)
    else:
        print("\nNext steps:")
        print(f"1. Upload {output_file} to your Supabase project")
        print("2. In Supabase dashboard: SQL Editor → New query")
        print("3. Paste the contents and execute")
        print("\nOr use psql:")
        print(f"  psql $DATABASE_URL < {output_file}")

    sqlite_session.close()


def main():
    parser = argparse.ArgumentParser(
        description="Migrate CyberIntel Summarizer from SQLite to PostgreSQL"
    )
    parser.add_argument(
        "--sqlite-path",
        default="cyberintel.db",
        help="Path to SQLite database file (default: cyberintel.db)",
    )
    parser.add_argument(
        "--output",
        "-o",
        default="migration.sql",
        help="Output SQL file path (default: migration.sql)",
    )
    parser.add_argument(
        "--postgres-url",
        help="PostgreSQL connection URL (e.g., postgresql://user:pass@host:5432/db)",  # pragma: allowlist secret
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Show statistics without writing files"
    )
    parser.add_argument(
        "--export-only", action="store_true", help="Only export to SQL file, don't import"
    )

    args = parser.parse_args()

    # If export-only, don't use postgres_url
    postgres_url = None if args.export_only else args.postgres_url

    print("=" * 60)
    print("  CyberIntel Summarizer: SQLite → PostgreSQL Migration")
    print("=" * 60)

    migrate_sqlite_to_postgresql(
        sqlite_path=args.sqlite_path,
        output_file=args.output,
        postgres_url=postgres_url,
        dry_run=args.dry_run,
    )

    print("\n" + "=" * 60)
    print("  Migration Complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
